name = "Squidcraft 2025"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf7c641b967f390d082e746b0df3dde13ff5816a0e5b15d057e07769a13de7fb"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
