name = "Squidcraft 2025"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0918c14283829ee14f3fc36a4bbf99fe817dbfe139b3bd74a041efd2d15829d2"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
