name = "Squidcraft 2025"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b93e9227270cd0e6c2a151d8472fa75adaa9d1918752dc95b23e7b9f13834c8"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
