name: Check packwiz refresh
on:
  pull_request: 
    branches: main
  push:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run check
        id: packwiz-check
        run: |
          sha512sum index.toml > ../hash
          sudo apt-get update
          sudo apt-get install -y golang
          go run github.com/packwiz/packwiz@latest refresh
          [ "$(cat ../hash)" = "$(sha512sum index.toml)" ] || exit 1
          echo Check passed!
